version: '3'
services:
  api-express:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/api
    container_name: api-express
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev:docker
