version: '3.1'

services:
  dbPostgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_USER: ${DOCKER_DATABASE_USER}
      POSTGRES_DB: ${DOCKER_DATABASE_NAME}

# docker-compose -f postgres-docker-compose.yml up  